---
image:
  # -- image repository
  repository: linuxserver/transmission
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 4.0.2

strategy:
  type: Recreate

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 9091

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: transmission.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - transmission.sestary.eu

# -- The common chart supports several add-ons.
addons:
  vpn:
    # -- Enable running a VPN in the pod to route traffic through a VPN
    enabled: true

    # -- Specify the VPN type. Valid options are `gluetun`.
    type: gluetun

    # -- Set the VPN container securityContext
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE

    # -- All variables specified here will be added to the vpn sidecar container
    # See the documentation of the VPN image for all config values
    env:
      VPN_SERVICE_PROVIDER: mulvard
      VPN_TYPE: openvpn
      WIREGUARD_PRIVATE_KEY: <path:secrets.enc.yaml#wireguard_private_key>
      SERVER_CITIES: Toronto

    # -- Optionally specify a livenessProbe, e.g. to check if the connection is
    # still being protected by the VPN
    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - if [ $(curl -s https://ipinfo.io/country) == 'CA' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 1

    networkPolicy:
      # -- If set to true, will deploy a network policy that blocks all outbound
      # traffic except traffic specified as allowed
      enabled: true

      # -- The egress configuration for your network policy, All outbound traffic
      # from the pod will be blocked unless specified here.
      # [[ref]](https://kubernetes.io/docs/concepts/services-networking/network-policies/)
      # [[recipes]](https://github.com/ahmetb/kubernetes-network-policy-recipes)
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            - port: 51820
              protocol: UDP

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config
    storageClass: longhorn

  downloads:
    enabled: true
    type: pvc
    accessMode: ReadWriteMany
    size: 25Ti
    mountPath: /downloads
    subPath: downloads/
    storageClass: "-"
    volumeName: truenas-media
