---
image:
  # -- image repository
  repository: dnsforge/xteve
  # -- image tag
  tag: latest

strategy:
  type: Recreate

probes:
  startup:
    spec:
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 60

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 34400

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true

    ingressClassName: nginx
    hosts:
      - host: xteve.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - xteve.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /home/xteve/conf
    storageClass: longhorn
