#ENC[AES256_GCM,data:K6vAmZMQolEMfrWQdFdNPnxjgEWjyrpbMws=,iv:QiDW1OKnNCn7E7CB2HqHoa3+NbmkciFIPsCuJLTJviw=,tag:WhOVSQbdUxKSx2G0qyuCTA==,type:comment]
bootstrap-password: ENC[AES256_GCM,data:omcOdKvZ7C7+Ozz2kfO8VkhyJN9iP9pPj1HIqlWADhRzRB+od9jzsHMaEcQc6iPjB+PdwJDNt8Ncx/d82/lAFQ==,iv:ITcj9zYS7W7IyJRAGwXAQvM+g23211KfhMPFZtKrY+I=,tag:n48P0qBwWeHYI1fzVDwCcw==,type:str]
bootstrap-token: ENC[AES256_GCM,data:8oba63c5JDyB32eAeuozmH2/65PSa7e8rU96hnVdrZrC40X3KlOZmaKBrTL2ONvyWDiHbl1cXqZZ/46yBBv59w==,iv:Q7e4xqqPrcndmxxH4cjIsmviZULKLnqBXzDcNQ30Rd8=,tag:4LtMTZDxqq7n2KFIOyGZ9g==,type:str]
secret-key: ENC[AES256_GCM,data:yffmkIryJoVl3FytTVYakeSgQNT+VeAwNmCQo8K4wEbTgylKj7R/L+loqsZVd/Q=,iv:DybNZg7JULzTcN7coMOtZadkFBhpeVEZh0OMdZOR6as=,tag:qQtNq44dIDRIjjGvxCMAmg==,type:str]
email-password: ENC[AES256_GCM,data:X/jf7hlF/RPpNV8VogEJoPtOiA==,iv:nrSAw/QvOmk3ivD5tWXxVqtQoGYLq2/wnxYBqrNGUUg=,tag:VSrI6+hnT8aNn6iGfCS/WQ==,type:str]
postgres-password: ENC[AES256_GCM,data:HYVvX8FqjPgb6iU6MVxbC4vA9BDWGIJJFuTS4ijGq8XpDbpV7LpGuQRsY0UCRquJ,iv:oT1qURmfK3MdBzdnhqEp0J2xMwAo0N7mf5gkQow/2vI=,tag:tmsYC3mcgwfVkU5WhddmqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nn2au3mxyk7ts5sjeta33tkrqn48a3u360k33tkwtr72ruc6za2qmppphs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETW02MGtYNjdLUy9UNjRU
            bEZjcDhvOENsQ3FaNW9wWEZOc1lxUzhkdHljClRuQytaaUtBMUxWNElNTDhlS0xw
            MXB2VlEyb3BaNDl1QmlIWGo4WWluam8KLS0tICtVbzdyRkljQ3lzbUVDWC9ieVhS
            b2tsT3gwQ0Rxdzk1MGQ5amVkNThXYUUKcCiH3BLOfwW8Qyg+7t8tiTWD2QBkfIUg
            /KN6K4xmEPg9ubxua9V2A/pibCD0T0Qka0JWH+gi0OPe7PVG/mGegQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-02T15:16:46Z"
    mac: ENC[AES256_GCM,data:03zvDVIjEpOnPSBZ0PHJnFsGwsNOF/yw9ANg1UtkMm26TLYOR/HlAKlGK78c3xIG3/CLjh1ZaGm1AKIIUJR6WDDgX8M2E9KsvtdhKdaIYWxXFKK2wws7wwD3Yftw1eFlOuhu7QKZsYtq2NpbMMTmNxMPn59/XWA5MsyLfJHMNNU=,iv:CUPxlPQz7WYYqwp8Ez0Nhf0tcFaR/Sow3/VS/vXmg2c=,tag:Q61gQ1k2dKFSmWhGnYEvaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
