secret-key: ENC[AES256_GCM,data:sV8Jaotg8+IlV2A5+3vJcKm8I+V7PuCnizDC+6cd652BBS+/ANfJHJ5uAYOOo0Y=,iv:Nb983bWFzXcDIayHEsywkREz2qorr6SjtIakhVMMt5M=,tag:E9z0nKYMhZMrIlfFXZTkPA==,type:str]
email-host: ENC[AES256_GCM,data:j7EgqJ04SHY3FxIOdZ0=,iv:M1StoW8YR8uwXie0a6/2fRKRWI/TLTCu0JKSilw0jlU=,tag:/XaGh0POLDmNljKOX/hTFw==,type:str]
email-from: ENC[AES256_GCM,data:d02nYpcTeBF6COhTnt4uxyu7,iv:hU5KpbuQ0cw5PAykWTLF3stXxp85A1R+3jHXDVqRNy4=,tag:aXKW099PNLjDgZOxSQe2Rg==,type:str]
email-password: ENC[AES256_GCM,data:prEwrl0N43PVK1UlzJla2KxcTw==,iv:gncfUq1cDUn/Ou8Y/SJfWcMQhPa7wDLMgkFuqxZAnf4=,tag:OVwmZlN1xU6g9hWsetFY/A==,type:str]
postgres-password: ENC[AES256_GCM,data:ZlJL+BkEPe+/o1WIB+oxfPtWOeO9W1Gz+dris4l1hBmvPa6ciGaJdXc1cMEkeFah,iv:EdBZYWeHz1xi0cwpqRhhxkhhPmDZ5tf67Y1gDTuFuvQ=,tag:n0uGbXxFvByvQqJvKepj3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nn2au3mxyk7ts5sjeta33tkrqn48a3u360k33tkwtr72ruc6za2qmppphs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0l3Z2dHSEU4ZVk1Zjlx
            ZE4yN1huT01YTVpLK0lLQXpCaWpyeTFkS3hRCmFnV3V4ejRJVXJ2cFVQVGNiZGh3
            eXFsR0tudS9PT21KdDFQQlk3Rmt1UEUKLS0tIHJUZm9NNzVMZXNkVlNpWEF0SldZ
            dkZIdVZBQmtGTWRBZVBPTktmUXU4cTgKwnG3WbfD1Hk1BSnLQP2c/d45NNk6lYsY
            670y+Z/BMI4afQhVdt8S8tdy2dg5bL0JeepSZ0hvNLjgYtLtieTdGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T22:04:47Z"
    mac: ENC[AES256_GCM,data:sEnD2Vpt+ASRdR7+EuuNuVqI3iUBM+yDjkXP+E2jkXwmdmMW1LcgEkJdGVvWUmb2FhQM82qQCtlxdow+ZNEHNyZYyBL7Qbum/NZJ1ylzWwUNFbSGsj8AYindFMwNd17qoMdeAgPglreBHddDKNK/EpXN3OklMDwsKirWNuYaI3k=,iv:fUfp+qIshk0/FmPd+/RPP55rsCXLHG1YvGrwT/0ymO4=,tag:Q+ayPG1Fd8TWrZDpXK1wcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
