---
authentik:
  avatars: none

  email:
    from: systems@sestary.eu
    host: mail.gandi.net
    username: systems@sestary.eu
    password: <path:secrets.enc.yaml#email-password>
    port: 587
    use_tls: true

  error_reporting:
    enabled: false

  postgresql:
    password: <path:secrets.enc.yaml#postgres-password>

  secret_key: <path:secrets.enc.yaml#secret-key>

image:
  repository: ghcr.io/sestary/authentik

envValueFrom:
  AUTHENTIK_BOOTSTRAP_EMAIL:
    secretKeyRef:
      name: authentik-bootstrap
      key: email
  AUTHENTIK_BOOTSTRAP_PASSWORD:
    secretKeyRef:
      name: authentik-bootstrap
      key: password
  AUTHENTIK_BOOTSTRAP_TOKEN:
    secretKeyRef:
      name: authentik-bootstrap
      key: token

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: sso.sestary.eu
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - sso.sestary.eu

postgresql:
  enabled: true
  postgresqlPassword: <path:secrets.enc.yaml#postgres-password>
  diagnosticMode:
    enabled: true
  image:
    tag: 15.2.0-debian-11-r26

redis:
  enabled: true
