---
authentik:
  avatars: none

  email:
    from: systems@sestary.eu
    host: mail.gandi.net
    username: systems@sestary.eu
    password: <path:secrets.enc.yaml#email-password>
    port: 587
    use_tls: true

  error_reporting:
    enabled: false

  postgresql:
    password: <path:secrets.enc.yaml#postgres-password>

  secret_key: <path:secrets.enc.yaml#secret-key>

envValueFrom:
  AUTHENTIK_BOOTSTRAP_EMAIL:
    secretKeyRef:
      name: authentik-bootstrap
      key: email
  AUTHENTIK_BOOTSTRAP_PASSWORD:
    secretKeyRef:
      name: authentik-bootstrap
      key: password
  AUTHENTIK_BOOTSTRAP_TOKEN:
    secretKeyRef:
      name: authentik-bootstrap
      key: token

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  ingressClassName: nginx
  hosts:
    - host: sso.sestary.eu
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - sso.sestary.eu
      secretName: ingress-tls

postgresql:
  enabled: true
  postgresqlPassword: <path:secrets.enc.yaml#postgres-password>

redis:
  enabled: true

volumes:
  - name: authentik-media-files
    configMap:
      name: authentik-media-files

volumeMounts:
  - name: authentik-media-files
    mountPath: "/web/dist/media"
    readOnly: true
