---
authentik:
  avatars: none

  email:
    from: systems@sestary.eu
    host: mail.gandi.net
    username: systems@sestary.eu
    password: <path:secrets.enc.yaml#email-password>
    port: 587
    use_tls: true

  error_reporting:
    enabled: false

  postgresql:
    password: <path:secrets.enc.yaml#postgres-password>

  secret_key: <path:secrets.enc.yaml#secret-key>

global:
  image:
    repository: ghcr.io/sestary/authentik
    pullPolicy: Always

server:
  env:
    - name: AUTHENTIK_BOOTSTRAP_EMAIL
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: email
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: password
    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: token

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: sso.sestary.eu
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - sso.sestary.eu

postgresql:
  enabled: true
  postgresqlPassword: <path:secrets.enc.yaml#postgres-password>

  persistence:
    storageClass: truenas-iscsi-csi

redis:
  enabled: true

  master:
    persistence:
      storageClass: truenas-iscsi-csi
