truenas_api_key: ENC[AES256_GCM,data:7heU2ecbH4EcuEO2n0cx9bHx6M/XNZeNyroZ5y4AnLkVADpzzcNxFERV4THm+juA0+mz5Tnfjh1nwyPEUMJry6tb,iv:aclRgjKDp0yCbiy1CV+pdRMmvQwg3ohzjL893hkvN1I=,tag:qO/fNIvbnRvD/BnO7qw0Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nn2au3mxyk7ts5sjeta33tkrqn48a3u360k33tkwtr72ruc6za2qmppphs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaXVjeWJNMzlXNTUvTmdv
            K05KOGYvVCtwRXRYS0E1MkJva1VQdGhla2dFCnJlUnZHaWpmd2JZUUVQVzg1V1pY
            cUQrOU1YenF2Z2E5cklBUytBazdaQU0KLS0tIEdHS25UNHV1ZUR3TVJ6SHEvTzhu
            UmtWRHhjSDFMWTJwZXBTbkZjcXNacTgKKbGH2Ly6om+XD0t8LWz/Fgva6kRxkqqx
            yWWjP1Lx51JjN+M8LuM65xosI8tMt6hGqYgf5XgiOMkwcmZBzikGJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T00:47:58Z"
    mac: ENC[AES256_GCM,data:Ck6aiPtUUyUEe/tZkQ4nuay9Q6ScYrczuSPtl2OxdSYXqYwJsDjgrz13fsZLQ1ghJQ8TLNGQXb8ceRuRUCqX1fWQ/4Ug2bWywzladwai0+asfYu2iiSOJ+oOA0a5zoUwuO6fcTSyRgSS5WlazlnrSyxu3H6gaCgjkEXnnrcZz+w=,iv:y0r5m/wNUualrmsvfC9Imi3gXbBs14Hs6z40irYh3QY=,tag:3HzoV4Nxg3I21Cww4CoePg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
