---
csiDriver:
  name: "org.democratic-csi.nfs"

node:
  kubeletHostPath: "/var/snap/microk8s/common/var/lib/kubelet"

driver:
  config:
    driver: node-manual

controller:
  # This manual driver does not support any of these functions
  externalProvisioner: 
    enabled: false
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: false
