---
csiDriver:
  name: "org.democratic-csi.node-manual"
  # See issue: https://github.com/democratic-csi/democratic-csi/issues/324
  attachRequired: false

node:
  kubeletHostPath: "/var/snap/microk8s/common/var/lib/kubelet"

controller:
  enabled: false

driver:
  config:
    driver: node-manual
