---
image:
  # -- image repository
  repository: lscr.io/linuxserver/radarr
  # -- image tag
  tag: 4.3.2.6857-ls164

strategy:
  type: Recreate

env:
  PUID: 1000
  PGID: 1000

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 7878

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: radarr.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - radarr.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 40Gi
    mountPath: /config
    storageClass: longhorn
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteMany
    size: 25Ti
    mountPath: /media
    storageClass: "-"
    volumeName: truenas-media-radarr
