version: 2
updates:
  - package-ecosystem: "docker"
    directory: "manifests/media/prowlarr"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[image update] "
  - package-ecosystem: "docker"
    directory: "manifests/media/radarr"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[image update] "
  - package-ecosystem: "docker"
    directory: "manifests/media/sonarr"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[image update] "
  - package-ecosystem: "docker"
    directory: "manifests/media/tautulli"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[image update] "
