---
applicationsets:
  - name: argocd
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/argocd/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "argocd"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'argocd'
        syncPolicy:
          syncStrategy:
            hook: {}
  - name: auth
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/auth/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "auth"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'auth-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: core
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/core/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "core"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'core-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: home
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/home/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "home"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'home-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: ingress
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/ingress/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "ingress"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'ingress-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: media
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/media/*
    template:
      metadata:
        name: '{{path.basename}}'
        annotations:
          argocd-image-updater.argoproj.io/image-list: default=lscr.io/linuxserver/{{path.basename}}:latest
          argocd-image-updater.argoproj.io/default.helm.image-name: image.repository
          argocd-image-updater.argoproj.io/default.helm.image-tag: image.tag
          argocd-image-updater.argoproj.io/update-strategy: digest
          argocd-image-updater.argoproj.io/write-back-method: git
      spec:
        project: "media"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'media-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: monitoring
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/monitoring/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "monitoring"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'monitoring-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
  - name: storage
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/storage/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "storage"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'storage-{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          syncStrategy:
            hook: {}
