applicationsets:
  - name: core 
    namespace: argocd
    generators:
      - git:
          repoURL: https://github.com/sestary/infrastructure
          revision: HEAD
          directories:
            - path: manifests/core/*
    template:
      metadata:
        name: '{{path.basename}}'
      spec:
        project: "core"
        source:
          repoURL: https://github.com/sestary/infrastructure
          targetRevision: HEAD
          path: '{{path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: '{{path.basename}}'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true

