---
projects:
  - name: argocd
    namespace: argocd
    description: ArgoCD related Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "argocd"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: auth
    namespace: argocd
    description: Authentication Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "auth-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: core
    namespace: argocd
    description: Kubernetes Core Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "core-*"
      - server: "https://kubernetes.default.svc"
        namespace: "kube-system"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: home
    namespace: argocd
    description: Home Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "home-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: ingress
    namespace: argocd
    description: Kubernetes Ingress Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "ingress-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: media
    namespace: argocd
    description: Media Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "media-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: monitoring
    namespace: argocd
    description: Kubernetes Monitoring Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "monitoring-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: storage
    namespace: argocd
    description: Kubernetes Storage Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "storage-*"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
