projects:
  - name: core
    namespace: argocd
    description: Kubernetes Core Services
    sourceRepos:
      - "https://github.com/sestary/infrastructure"
    destinations:
      - server: "https://kubernetes.default.svc"
        namespace: "core-*"
      - server: "https://kubernetes.default.svc"
        namespace: "kube-system"
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
