mini_token: ENC[AES256_GCM,data:DO2tqYWLdlLyrSTmEKU8/XHZUC0=,iv:d0HYdUVJXTIZPvCgNgiXF1zegA2qYPtrZc0wc83tQms=,tag:Tl2GyRkNvNBnK17pyXu+Rg==,type:str]
mini_url: ENC[AES256_GCM,data:rHOjG0wIrxBktZKsRDKUajNxRsnq6MMhqjPS6EzXYS0abqI7Fhf0TF3NPfRiX/SfXro=,iv:iFrYk6VJPiYjhobFEMUMMNuOzooEB2/lyGl3dgk1uAY=,tag:ms9Yxah16T+hVzXYYhZloA==,type:str]
xl_token: ENC[AES256_GCM,data:LdOmpU5iiyimIvd1Vz7fflWPZTg=,iv:BRPfROILb/MTpmD7SPuaNFFSwh4KdDOqtHryTXysqnE=,tag:J7URd4vjlWEpSkF8cLZVcQ==,type:str]
xl_url: ENC[AES256_GCM,data:H+aDqh4TmWhzWrOJ8GsPtny6Do3hOCCY1GeA+Xf0UvjbS5IJVt2n0LPOjwq4v4d9lHk=,iv:3FW6eBYHmIgy9W3vlD9OUCLKvhqNVC74ovIf3iAgTe8=,tag:kLfr7RBkZys7nQy8aw7Vfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nn2au3mxyk7ts5sjeta33tkrqn48a3u360k33tkwtr72ruc6za2qmppphs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanlSNkNPZUVjQ1dWNTRO
            c29oMm9vR04rcGNGZzdOenJSaVdkdmtZTURrCnlzOE5kbXJRU2o0SXRFUWFEa1lO
            eGVCeFRNeUZ6MEs2S1YreHpPd1NsY28KLS0tIGVlenMzR3JWeHNGYWhTdEdzSW01
            UHMvUGRmR1l3MlloaFY5UVo3eFVYbFkKfhr3e9DBf8gSqydIDU+8MpTTs0J9NE0T
            MGVgiypKtv7b3l+gWQnd6DEIqtHykqhHhKH6Vjfk0C1kq7xtd2WH/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T20:00:15Z"
    mac: ENC[AES256_GCM,data:Nw5G/xGgWcb5QtxJdvR4Lvq8Zf4md7NmRA5cvo0QkE6ap1z6iITnl0BS8XxVcMqUEbEvN1W5UnORglkVzI1s9qW1Z2LDLESmgfcUyjGwselOZeE6XpSv899oj1+LJK1NDFVJVxK+RWNv4Z0cq+jKFHXkNhjmuxxg/sJiMyp8jA4=,iv:lO4g7nruigYLbkZPHNUf4tyrmosPTqPRR2AsZpRR/o0=,tag:cgs3hLX1Ek5vIJhDC8HDMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
