repoServer:
  initContainers:
    - name: helm-plugin-setup
      image: ubuntu
      command:
        - sh
        - -c
        - |
            apt-get update && apt-get install -y ca-certificates wget
            wget https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz -O - | tar xz && mv linux-amd64/helm /tools/helm && chmod +x /tools/helm
            wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.0/kustomize_v5.0.0_linux_amd64.tar.gz -O - | tar xz && mv kustomize /tools/kustomize && chmod a+x /tools/kustomize
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /tools/jq && chmod +x /tools/jq
            wget https://github.com/mikefarah/yq/releases/download/v4.24.5/yq_linux_amd64 -O /tools/yq && chmod +x /tools/yq
      volumeMounts:
        - mountPath: /etc/ssl
          name: ssl-files
        - mountPath: /tools
          name: helm-plugin-tools


  extraContainers:
    - name: helm-plugin
      command: [/var/run/argocd/argocd-cmp-server]
      args: [--loglevel, debug]
      image: ubuntu
      env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
            # securityContext:
            #runAsNonRoot: true
            #runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /etc/ssl
          name: ssl-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /helm-working-dir
          name: helm-plugin-tmp
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml
          name: helm-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/generate.sh
          subPath: generate.sh
          name: helm-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/get-parameters.sh
          subPath: get-parameters.sh
          name: helm-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/init.sh
          subPath: init.sh
          name: helm-plugin-config
        - mountPath: /usr/local/bin
          name: helm-plugin-tools
    - name: helm-kustomize-plugin
      command: [/var/run/argocd/argocd-cmp-server]
      args: [--loglevel, debug]
      image: ubuntu
      env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
            #securityContext:
        #runAsNonRoot: true
        #runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /etc/ssl
          name: ssl-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /helm-working-dir
          name: helm-plugin-tmp
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml
          name: helm-kustomize-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/generate.sh
          subPath: generate.sh
          name: helm-kustomize-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/get-parameters.sh
          subPath: get-parameters.sh
          name: helm-kustomize-plugin-config
        - mountPath: /var/run/argocd/helm-plugin/init.sh
          subPath: init.sh
          name: helm-kustomize-plugin-config
        - mountPath: /usr/local/bin
          name: helm-plugin-tools

  volumes:
    - configMap:
        name: helm-plugin-config
      name: helm-plugin-config
    - configMap:
        name: helm-kustomize-plugin-config
      name: helm-kustomize-plugin-config
    - emptyDir: {}
      name: ssl-files
    - emptyDir: {}
      name: helm-plugin-tmp
    - emptyDir: {}
      name: helm-plugin-tools
