---
image:
  # -- image repository
  repository: lscr.io/linuxserver/plex
  # -- image tag
  tag: 1.32.6.7557-1cf77d501-ls186

strategy:
  type: Recreate

env:
  PUID: 1000
  PGID: 1000

# -- Configures service settings for the chart.
service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 32400

# This turns on the GPU
resources:
  limits:
    cpu: 16
    memory: "32Gi"

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 300Gi
    mountPath: /config
    storageClass: truenas-iscsi-csi
  transcode:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 200Gi
    mountPath: /transcode
    storageClass: truenas-iscsi-csi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteMany
    size: 25Ti
    mountPath: /media
    storageClass: "-"
    volumeName: truenas-media-plex
  srv:
    enabled: true
    type: pvc
    accessMode: ReadWriteMany
    size: 25Ti
    mountPath: /srv/video
    subPath: video/
    storageClass: "-"
    volumeName: truenas-media-plex-srv
