---
longhorn:
  csi:
    # The path on MicroK8s isn't the same as normal since it's a snap
    kubeletRootDir: "/var/snap/microk8s/common/var/lib/kubelet"

  defaultSettings:
    allowRecurringJobWhileVolumeDetached: true
    defaultDataLocality: best-effort
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    replicaAutoBalance: best-effort
    removeSnapshotsDuringFilesystemTrim: true

  persistence:
    defaultClassReplicaCount: 2
    reclaimPolicy: Delete
    migratable: false
    removeSnapshotsDuringFilesystemTrim: true

  ingress:
    enabled: true

    ingressClassName: nginx

    host: longhorn.sestary.eu

    tls: true

    path: /

    annotations:
      nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-sestary-sestary.auth-authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
      nginx.ingress.kubernetes.io/auth-signin: |-
        https://longhorn.sestary.eu/outpost.goauthentik.io/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
