---
image:
  # -- image repository
  repository: ghcr.io/flaresolverr/flaresolverr
  # -- image tag
  tag: v3.3.21

strategy:
  type: Recreate

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 9696

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true

    annotations:
      nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-sestary-outpost.auth-authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
      nginx.ingress.kubernetes.io/auth-signin: |-
        https://prowlarr.sestary.eu/outpost.goauthentik.io/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;

    ingressClassName: nginx
    hosts:
      - host: solverr.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - solverr.sestary.eu
