---
image:
  # -- image repository
  repository: koush/scrypted
  # -- image tag
  tag: 18-bullseye-lite.s6-v0.7.29
strategy:
  type: Recreate

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 11080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: scrypted.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - scrypted.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 40Gi
    mountPath: /server/volume
    storageClass: longhorn
