---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: democratic-csi
    namespace: core-democratic
    releaseName: democratic-csi-nfs
    repo: https://democratic-csi.github.io/charts/
    valuesFile: values-nfs.yaml
    version: 0.13.5
