---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-media-radarr
spec:
  capacity:
    storage: 25Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: truenas-media-radarr  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: nas1.on.sestary.eu
      share: /mnt/common/media
      node_attach_driver: nfs
      provisioner_driver: node-manual
