---
alertmanager:
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false
      network: true

  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"

    ingressClassName: nginx

    hosts:
      - alertmanager.on.sestary.eu
    paths:
      - /

    tls:
      - hosts:
          - alertmanager.on.sestary.eu
        secretName: ingress-tls-alertmanger

prometheus:
  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"

    ingressClassName: nginx

    hosts:
      - prometheus.on.sestary.eu
    paths:
      - /

    tls:
      - hosts:
          - prometheus.on.sestary.eu
        secretName: ingress-tls-prometheus

# Using Grafana Cloud
grafana:
  enabled: false

# MicroK8s doesn't use anye of these
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
