---
image:
  # -- image repository
  repository: lscr.io/linuxserver/jellyseerr
  # -- image tag
  tag: v4.35.10-ls152

strategy:
  type: Recreate

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 5055

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true

    ingressClassName: nginx
    hosts:
      - host: requests.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - requests.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /config
    storageClass: longhorn
