---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kured
    namespace: core-kured
    releaseName: kubred
    repo: https://kubereboot.github.io/charts
    valuesFile: values.yaml
    version: 4.4.2
