loki-url: ENC[AES256_GCM,data:SoopZnNUYpdMdZUX6pyI5J4J/Y9lkPeXTQfKQWucYj7GSekfYNyF822t8kdwyO3sidcYLcStIXM=,iv:dKvkBrUhmqY4AW7h32rOABket4liU6pHg+RDinME8Qk=,tag:TCTT63TQbVmoV5Q08rNoHA==,type:str]
tennent-id: ENC[AES256_GCM,data:0x9pbT75,iv:nGx4tBjjpnLQOrJ6P+KONOr7Lu4d2TQmNE77UOCBhAc=,tag:OzKobDZRJfoNgrIysn50mA==,type:str]
access-policy-token: ENC[AES256_GCM,data:GEQaBtzJPEfGBVT5YfufBNL2MJhnmDP1ZKq68HaQpdqkXr2NThumvhN/Mu6C3Ho6/tN7/rSpS5EZOR2TgjXSEXSM5+MzV16Kg3WB8dHtL6KRaEmzlA15ccrnE10pinduSX/9sqh5Jx96tA3l59fahGnqjyc=,iv:yU0SwynLuejiRIid/vunwblg7SHdW5BhKh6N+yVFYao=,tag:Kr+HkimiAhxWsGoRfOvTVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nn2au3mxyk7ts5sjeta33tkrqn48a3u360k33tkwtr72ruc6za2qmppphs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOE9Pa0VIYVJBbVcrSy9H
            VlhUamlrTGRMWlRuNzBCcWorSy9scjlCcXg4CitJamxMNjhycTYrVWJ1TlFONzJx
            SklMbkw3ZmNrYmt4eU5pSXZpYm1Ba28KLS0tIGo3b3RiZE9BVWRPQWhGSUNEZUd6
            YmF6SHUrNThsSVRuTk5va2JXSnkyYnMKkmQh/jihHs2sVWH4LMWprmNur/mSh7xb
            zs7hXdl1bSjEqSkHajeSu3350yctLnPj/jQC+jQ91PixbRyXDXgjBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T19:31:33Z"
    mac: ENC[AES256_GCM,data:6Rt0+Zm+Xt0sw1kJwSOnFWdNnE+p2R3NV4tNofMKuDF+mztta55kQ0sL2Gy7DSFlvx3f4H8odBzyFORlISFRYuY5Bua4ry92EKO10piHSIS9zMLRYNLMA9gaiIMakeqPcUoaM3zDg3+HnsXAIz+oqmpbIERepIsy4IU5UkFbJEA=,iv:3Z7Th4BITCQuMUzs+IZtK23GswiTw/wN5FSD7A5dnE8=,tag:AHdea4ziEXHbnzi5pIhMsg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
