---
agent:
  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
         role = "pod"
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [
         loki.relabel.grafana_cloud.receiver,
        ]
      }

      loki.relabel "grafana_cloud" {
        forward_to = [
          loki.write.grafana_cloud.receiver,
        ]

        rule {
          source_labels = [
            "__meta_kubernetes_pod_node_name",
          ]
          target_label = "__host__"
        }

        rule {
          action = "labelmap"
          regex = "__meta_kubernetes_pod_label_(.+)"
        }

        rule {
          action = "replace"
          replacement = "$1"
          separator = "/"
          source_labels = [
            "__meta_kubernetes_namespace",
            "__meta_kubernetes_pod_name",
          ]
          target_label = "job"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_namespace",
          ]
          target_label ="namespace"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_pod_name",
          ]
          target_label = "pod"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_pod_container_name",
          ]
          target_label = "container"
        }

        rule {
          replacement = "/var/log/pods/*$1/*.log"
          separator = "/"
          source_labels = [
            "__meta_kubernetes_pod_uid",
            "__meta_kubernetes_pod_container_name",
          ]
          target_label = "__path__"
        }
      }

      loki.write "grafana_cloud" {

        endpoint {
          url = "<path:secrets.enc.yaml#loki-url>"

          basic_auth {
            username = "<path:secrets.enc.yaml#tennent-id>"
            password = "<path:secrets.enc.yaml#access-policy-token>"
          }

          batch_size = "262144B"
        }
      }

configReloader:
  enabled: false
