---
agent:
  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
         role = "pod"
      }

      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets

        rule {
          action = "drop"
          source_labels = [
            "__meta_kubernetes_pod_node_name",
          ]
          regex = env("HOSTNAME")
        }

        rule {
          source_labels = [
            "__meta_kubernetes_pod_node_name",
          ]
          target_label = "node_name"
        }

        rule {
          source_labels = [
            "__meta_kubernetes_pod_container_image",
          ]
          target_label = "image"
        }

        rule {
          action = "labelmap"
          regex = "__meta_kubernetes_pod_label_(.+)"
        }

        rule {
          action = "replace"
          replacement = "$1"
          separator = "/"
          source_labels = [
            "__meta_kubernetes_namespace",
            "__meta_kubernetes_pod_name",
          ]
          target_label = "job"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_namespace",
          ]
          target_label ="namespace"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_pod_name",
          ]
          target_label = "pod"
        }

        rule {
          action = "replace"
          source_labels = [
            "__meta_kubernetes_pod_container_name",
          ]
          target_label = "container"
        }

        rule {
          replacement = "/var/log/pods/*$1/*.log"
          separator = "/"
          source_labels = [
            "__meta_kubernetes_pod_uid",
            "__meta_kubernetes_pod_container_name",
          ]
          target_label = "__path__"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [
         loki.process.pods.receiver,
        ]
      }

      loki.process "pods" {
        stage.labels {
          values = {
            level  = "",         // Sets up an 'level' label, based on the 'level' extracted value.
          }
        }

        forward_to = [
         loki.write.grafana_cloud.receiver,
        ]
      }

      loki.write "grafana_cloud" {
        endpoint {
          url = "<path:secrets.enc.yaml#loki-url>"

          basic_auth {
            username = "<path:secrets.enc.yaml#tennent-id>"
            password = "<path:secrets.enc.yaml#access-policy-token>"
          }

          batch_size = "256KiB"
        }
      }

configReloader:
  enabled: false
