---
agent:
  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
         role = "pod"
      }

      loki.source.kubernetes "pds" {
        targets    = discover.kubernetes.pods.targets
        forward_to = [
         loki.write.grafana_cloud.receiver,
        ]
      }

      loki.write "grafana_cloud" {
        endpoint {
          url = <path:secrets.enc.yaml#loki-url>
          basic_auth {
            username: <path:secrets.enc.yaml#loki-tennent>
            password: <path:secrets.enc.yaml#loki-token>
          }
        }
      }

configReloader:
  enabled: false
