apiVersion: v2
name: nginx
description: Deploy NGINX Ingress

type: application

# This is the chart version, but is ignored by ArgoCD
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: 4.5.2
    repository: https://kubernetes.github.io/ingress-nginx
