---
controller:
  replicaCount: 2

  extraArgs:
    default-ssl-certificate: "ingress-nginx/default-tls-certificate"

  ingressClassResource:
    # We want this ingress to be the default
    default: true

  service:
    externalTrafficPolicy: Local
