---
controller:
  replicaCount: 2

  config:
    allow-snippet-annotations: true
    annotations-risk-level: critical
    force-ssl-redirect: true

  extraArgs:
    default-ssl-certificate: "ingress-nginx/default-tls-certificate"

  ingressClassResource:
    # We want this ingress to be the default
    default: true

  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
    externalTrafficPolicy: Local
    externalIPs:
      - 10.2.0.60
