---
image:
  # -- image repository
  repository: oznu/homebridge
  # -- image tag
  tag: 2023-01-08

strategy:
  type: Recreate

# Needed due to the HomeKit plugin
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 8581

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: homebridge.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - homebridge.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 40Gi
    mountPath: /homebridge
    storageClass: longhorn
  config-nas:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 40Gi
    mountPath: /homebridge2
    storageClass: truenas-iscsi-csi
