---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi
