apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:cert-manager-k8s-cloudflare-com
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: core-cert-manager
