---
image:
  # -- image repository
  repository: lscr.io/linuxserver/emby
  # -- image tag
  tag: 4.7.11.0-ls147

strategy:
  type: Recreate

env:
  PUID: 1000
  PGID: 1000

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 8096

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: emby.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - emby.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 40Gi
    mountPath: /config
    storageClass: truenas-iscsi-csi
  transcode:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 200Gi
    mountPath: /transcode
    storageClass: truenas-iscsi-csi
  media:
    enabled: true
    type: pvc
    accessMode: ReadWriteMany
    size: 25Ti
    mountPath: /media
    storageClass: "-"
    volumeName: truenas-media-emby
